[project]
name = "agentsai"
version = "0.1.0"
description = "Agents AI to build content."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pytrends>=4.9.2",
]

[dependency-groups]
dev = [
    "pytest>=8.3.5",
    "ruff>=0.11.10",
]
